-- ============================================================================
-- SQL SCRIPT - INFRAESTRUCTURA CENTRO DE MANDO DIGITAL LINKTIC
-- ============================================================================
-- Instancia: https://klecvgchqqbkasedxtxj.supabase.co
-- Schema: centro_mando
-- Aislamiento completo de Autenticación, RBAC y Negocio.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS centro_mando;

-- ============================================================================
-- 1. TABLAR DE SEGURIDAD Y CONTROL (PROFILES Y ACCESOS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS centro_mando.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    user_role TEXT DEFAULT 'viewer',
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE centro_mando.profiles DROP CONSTRAINT IF EXISTS profiles_user_role_check;
ALTER TABLE centro_mando.profiles ADD CONSTRAINT profiles_user_role_check
    CHECK (user_role IN ('superadmin', 'admin', 'viewer'));

CREATE TABLE IF NOT EXISTS centro_mando.user_screen_access (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    screen_key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, screen_key)
);

-- ============================================================================
-- 2. FUNCIONES Y TRIGGERS DE SEGURIDAD (SECURITY DEFINER)
-- ============================================================================

CREATE OR REPLACE FUNCTION centro_mando.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM centro_mando.profiles
        WHERE id = auth.uid() AND user_role IN ('admin', 'superadmin')
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION centro_mando.is_superadmin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM centro_mando.profiles
        WHERE id = auth.uid() AND user_role = 'superadmin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION centro_mando.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO centro_mando.profiles (id, user_role, full_name)
    VALUES (
        new.id,
        'viewer', -- Rol por defecto
        COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'username')
    )
    ON CONFLICT (id) DO UPDATE
        SET full_name = COALESCE(EXCLUDED.full_name, centro_mando.profiles.full_name);
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created_centro_mando ON auth.users;
CREATE TRIGGER on_auth_user_created_centro_mando
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE centro_mando.handle_new_user();

-- ============================================================================
-- 3. TABLAS DE NEGOCIO Y MÉTRICAS
-- ============================================================================

-- A. Conversación en Medios
CREATE TABLE IF NOT EXISTS centro_mando.medios_perfiles (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT '0%',
    sentimiento INTEGER DEFAULT 0,
    notas INTEGER DEFAULT 0,
    tendencia_semanal JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.medios_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- B. Conversación en Redes
CREATE TABLE IF NOT EXISTS centro_mando.social_perfiles (
    id TEXT PRIMARY KEY, -- 'instagram', 'facebook', 'x', 'tiktok'
    seguidores TEXT DEFAULT '0',
    interacciones INTEGER DEFAULT 0,
    alcance TEXT DEFAULT '0',
    posts INTEGER DEFAULT 0,
    sentimiento INTEGER DEFAULT 0,
    tendencia JSONB DEFAULT '[]'::jsonb,
    top_posts JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.social_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    red TEXT NOT NULL,
    usuario TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- C. Mapa de Colombia
CREATE TABLE IF NOT EXISTS centro_mando.actores_colombia (
    id TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    capital TEXT,
    lat NUMERIC,
    lng NUMERIC,
    tema TEXT,
    keywords JSONB DEFAULT '[]'::jsonb,
    sentimiento TEXT,
    sentimiento_pct JSONB,
    volumen NUMERIC DEFAULT 0,
    plataformas JSONB DEFAULT '{"Instagram": 0}'::jsonb,
    resumen TEXT,
    tendencia TEXT,
    pct_cambio NUMERIC DEFAULT 0,
    top_hashtags JSONB DEFAULT '[]'::jsonb,
    update_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- 4. SEGURIDAD (ROW LEVEL SECURITY)
-- ============================================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE centro_mando.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.user_screen_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.medios_perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.medios_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.social_perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.social_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.actores_colombia ENABLE ROW LEVEL SECURITY;

-- Políticas para perfiles
DROP POLICY IF EXISTS "cne perfil lectura autenticados" ON centro_mando.profiles;
CREATE POLICY "cne perfil lectura autenticados" ON centro_mando.profiles
    FOR SELECT TO authenticated USING (id = auth.uid() OR centro_mando.is_superadmin());

DROP POLICY IF EXISTS "cne perfil escritura superadmin" ON centro_mando.profiles;
CREATE POLICY "cne perfil escritura superadmin" ON centro_mando.profiles
    FOR ALL TO authenticated USING (centro_mando.is_superadmin()) WITH CHECK (centro_mando.is_superadmin());

-- Políticas para acceso a pantallas
DROP POLICY IF EXISTS "cne accesos lectura autenticados" ON centro_mando.user_screen_access;
CREATE POLICY "cne accesos lectura autenticados" ON centro_mando.user_screen_access
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR centro_mando.is_superadmin());

DROP POLICY IF EXISTS "cne accesos escritura superadmin" ON centro_mando.user_screen_access;
CREATE POLICY "cne accesos escritura superadmin" ON centro_mando.user_screen_access
    FOR ALL TO authenticated USING (centro_mando.is_superadmin()) WITH CHECK (centro_mando.is_superadmin());

-- Políticas genéricas para tablas de negocio:
-- - Lectura para cualquier usuario autenticado (justificado para visualizar métricas en el dashboard).
-- - Escritura completa restringida a administradores (según la función centro_mando.is_admin()).

DO $$
DECLARE
    table_name TEXT;
    tables_list TEXT[] := ARRAY[
        'medios_perfiles', 'medios_feed',
        'social_perfiles', 'social_feed',
        'actores_colombia'
    ];
BEGIN
    FOREACH table_name IN ARRAY tables_list
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Lectura autenticados" ON centro_mando.%I', table_name);
        EXECUTE format('CREATE POLICY "Lectura autenticados" ON centro_mando.%I FOR SELECT TO authenticated USING (true)', table_name);

        EXECUTE format('DROP POLICY IF EXISTS "Escritura administradores" ON centro_mando.%I', table_name);
        EXECUTE format('CREATE POLICY "Escritura administradores" ON centro_mando.%I FOR ALL TO authenticated USING (centro_mando.is_admin()) WITH CHECK (centro_mando.is_admin())', table_name);
    END LOOP;
END $$;

-- ============================================================================
-- 5. GRANTS Y PERMISOS DE ACCESO API (POSTGREST)
-- ============================================================================

GRANT USAGE ON SCHEMA centro_mando TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA centro_mando TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA centro_mando TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA centro_mando TO authenticated;

-- ============================================================================
-- 6. SEMILLAS DE DATOS INICIALES (DATOS DE PRUEBA)
-- ============================================================================

-- Conversación en Medios y Conversación en Redes: sin datos de ejemplo.
-- Estas tablas quedan vacías; el contenido real se carga desde la pestaña
-- de edición de cada módulo en el dashboard.

-- Mapa de Colombia (semilla neutra, sin lenguaje electoral/CNE)
INSERT INTO centro_mando.actores_colombia
(id, nombre, capital, lat, lng, tema, keywords, sentimiento, sentimiento_pct, volumen, plataformas, resumen, tendencia, pct_cambio, top_hashtags, update_time)
VALUES
('08', 'Atlántico', 'Barranquilla', 10.675, -74.973, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Atlántico","Tendencias2026"]', 'neutral', '{"neutral":42,"negativo":11,"positivo":47}', 36500, '{"Instagram":36500}', 'Conversación en Instagram en Atlántico centrada en tendencias digitales y de marca. Capital: Barranquilla.', 'estable', 0.8, '["#Atlántico","#Tendencias2026"]', 'hace 4 min'),
('11', 'Santafé de Bogotá D.C', 'Bogotá', 4.286, -74.211, 'Debates y opiniones de la comunidad digital', '["Instagram","Santafé","Tendencias2026"]', 'neutral', '{"neutral":32,"negativo":14,"positivo":54}', 51800, '{"Instagram":51800}', 'Conversación en Instagram en Santafé de Bogotá D.C centrada en tendencias digitales y de marca. Capital: Bogotá.', 'baja', 6, '["#SantafédeBogotáDC","#Tendencias2026"]', 'hace 5 min'),
('13', 'Bolívar', 'Cartagena', 9.125, -74.764, 'Contenido educativo e institucional en redes', '["Instagram","Bolívar","Tendencias2026"]', 'positivo', '{"neutral":22,"negativo":17,"positivo":61}', 36380, '{"Instagram":36380}', 'Conversación en Instagram en Bolívar centrada en tendencias digitales y de marca. Capital: Cartagena.', 'sube', 7.4, '["#Bolívar","#Tendencias2026"]', 'hace 6 min'),
('15', 'Boyacá', 'Tunja', 5.849, -73.295, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Boyacá","Tendencias2026"]', 'positivo', '{"neutral":12,"negativo":20,"positivo":68}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Boyacá centrada en tendencias digitales y de marca. Capital: Tunja.', 'estable', 9.8, '["#Boyacá","#Tendencias2026"]', 'hace 7 min'),
('17', 'Caldas', 'Manizales', 5.351, -75.38, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Caldas","Tendencias2026"]', 'negativo', '{"neutral":37,"negativo":23,"positivo":40}', 24080, '{"Instagram":24080}', 'Conversación en Instagram en Caldas centrada en tendencias digitales y de marca. Capital: Manizales.', 'baja', 13, '["#Caldas","#Tendencias2026"]', 'hace 8 min'),
('18', 'Caquetá', 'Florencia', 0.667, -73.81, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Caquetá","Tendencias2026"]', 'neutral', '{"neutral":45,"negativo":8,"positivo":47}', 17300, '{"Instagram":17300}', 'Conversación en Instagram en Caquetá centrada en tendencias digitales y de marca. Capital: Florencia.', 'sube', 15.4, '["#Caquetá","#Tendencias2026"]', 'hace 9 min'),
('19', 'Cauca', 'Popayán', 2.324, -76.835, 'Debates y opiniones de la comunidad digital', '["Instagram","Cauca","Tendencias2026"]', 'neutral', '{"neutral":35,"negativo":11,"positivo":54}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Cauca centrada en tendencias digitales y de marca. Capital: Popayán.', 'estable', -3.7, '["#Cauca","#Tendencias2026"]', 'hace 10 min'),
('20', 'Cesar', 'Valledupar', 9.29, -73.524, 'Contenido educativo e institucional en redes', '["Instagram","Cesar","Tendencias2026"]', 'positivo', '{"neutral":25,"negativo":14,"positivo":61}', 25820, '{"Instagram":25820}', 'Conversación en Instagram en Cesar centrada en tendencias digitales y de marca. Capital: Valledupar.', 'baja', -0.8, '["#Cesar","#Tendencias2026"]', 'hace 11 min'),
('23', 'Córdoba', 'Montería', 8.531, -75.697, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Córdoba","Tendencias2026"]', 'positivo', '{"neutral":15,"negativo":17,"positivo":68}', 28640, '{"Instagram":28640}', 'Conversación en Instagram en Córdoba centrada en tendencias digitales y de marca. Capital: Montería.', 'sube', 2.9, '["#Córdoba","#Tendencias2026"]', 'hace 3 min'),
('25', 'Cundinamarca', 'Bogotá', 4.755, -74.174, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Cundinamarca","Tendencias2026"]', 'neutral', '{"neutral":40,"negativo":20,"positivo":40}', 37520, '{"Instagram":37520}', 'Conversación en Instagram en Cundinamarca centrada en tendencias digitales y de marca. Capital: Bogotá.', 'estable', 7.8, '["#Cundinamarca","#Tendencias2026"]', 'hace 4 min'),
('27', 'Chocó', 'Quibdó', 6.016, -77.004, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Chocó","Tendencias2026"]', 'negativo', '{"neutral":30,"negativo":23,"positivo":47}', 19220, '{"Instagram":19220}', 'Conversación en Instagram en Chocó centrada en tendencias digitales y de marca. Capital: Quibdó.', 'baja', 8.8, '["#Chocó","#Tendencias2026"]', 'hace 5 min'),
('41', 'Huila', 'Neiva', 2.665, -75.602, 'Debates y opiniones de la comunidad digital', '["Instagram","Huila","Tendencias2026"]', 'neutral', '{"neutral":38,"negativo":8,"positivo":54}', 25400, '{"Instagram":25400}', 'Conversación en Instagram en Huila centrada en tendencias digitales y de marca. Capital: Neiva.', 'sube', 12.9, '["#Huila","#Tendencias2026"]', 'hace 6 min'),
('44', 'La Guajira', 'Riohacha', 11.452, -72.493, 'Contenido educativo e institucional en redes', '["Instagram","La","Tendencias2026"]', 'positivo', '{"neutral":28,"negativo":11,"positivo":61}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en La Guajira centrada en tendencias digitales y de marca. Capital: Riohacha.', 'estable', 16, '["#LaGuajira","#Tendencias2026"]', 'hace 7 min'),
('47', 'Magdalena', 'Santa Marta', 10.189, -74.265, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Magdalena","Tendencias2026"]', 'positivo', '{"neutral":18,"negativo":14,"positivo":68}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Magdalena centrada en tendencias digitales y de marca. Capital: Santa Marta.', 'baja', -3.8, '["#Magdalena","#Tendencias2026"]', 'hace 8 min'),
('50', 'Meta', 'Villavicencio', 3.218, -73.111, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Meta","Tendencias2026"]', 'neutral', '{"neutral":43,"negativo":17,"positivo":40}', 28400, '{"Instagram":28400}', 'Conversación en Instagram en Meta centrada en tendencias digitales y de marca. Capital: Villavicencio.', 'sube', -0.1, '["#Meta","#Tendencias2026"]', 'hace 9 min'),
('54', 'Norte de Santander', 'Cúcuta', 7.871, -72.949, 'Debates y opiniones de la comunidad digital', '["Instagram","Norte","Tendencias2026"]', 'negativo', '{"neutral":23,"negativo":23,"positivo":54}', 30680, '{"Instagram":30680}', 'Conversación en Instagram en Norte de Santander centrada en tendencias digitales y de marca. Capital: Cúcuta.', 'baja', 6.8, '["#NortedeSantander","#Tendencias2026"]', 'hace 11 min'),
('63', 'Quindío', 'Armenia', 4.498, -75.702, 'Contenido educativo e institucional en redes', '["Instagram","Quindío","Tendencias2026"]', 'positivo', '{"neutral":31,"negativo":8,"positivo":61}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en Quindío centrada en tendencias digitales y de marca. Capital: Armenia.', 'sube', 9.2, '["#Quindío","#Tendencias2026"]', 'hace 3 min'),
('66', 'Risaralda', 'Pereira', 5.061, -75.893, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Risaralda","Tendencias2026"]', 'positivo', '{"neutral":21,"negativo":11,"positivo":68}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Risaralda centrada en tendencias digitales y de marca. Capital: Pereira.', 'estable', 13.2, '["#Risaralda","#Tendencias2026"]', 'hace 4 min'),
('68', 'Santander', 'Bucaramanga', 6.611, -73.428, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Santander","Tendencias2026"]', 'neutral', '{"neutral":46,"negativo":14,"positivo":40}', 34640, '{"Instagram":34640}', 'Conversación en Instagram en Santander centrada en tendencias digitales y de marca. Capital: Bucaramanga.', 'baja', 17.7, '["#Santander","#Tendencias2026"]', 'hace 5 min'),
('70', 'Sucre', 'Sincelejo', 9.135, -75.206, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Sucre","Tendencias2026"]', 'neutral', '{"neutral":36,"negativo":17,"positivo":47}', 20180, '{"Instagram":20180}', 'Conversación en Instagram en Sucre centrada en tendencias digitales y de marca. Capital: Sincelejo.', 'sube', -4.6, '["#Sucre","#Tendencias2026"]', 'hace 6 min'),
('73', 'Tolima', 'Ibagué', 4.076, -75.212, 'Debates y opiniones de la comunidad digital', '["Instagram","Tolima","Tendencias2026"]', 'neutral', '{"neutral":26,"negativo":20,"positivo":54}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Tolima centrada en tendencias digitales y de marca. Capital: Ibagué.', 'estable', -0.3, '["#Tolima","#Tendencias2026"]', 'hace 7 min'),
('76', 'Valle del Cauca', 'Cali', 3.98, -76.566, 'Contenido educativo e institucional en redes', '["Instagram","Valle","Tendencias2026"]', 'positivo', '{"neutral":16,"negativo":23,"positivo":61}', 47900, '{"Instagram":47900}', 'Conversación en Instagram en Valle del Cauca centrada en tendencias digitales y de marca. Capital: Cali.', 'baja', 5.4, '["#ValledelCauca","#Tendencias2026"]', 'hace 8 min'),
('81', 'Arauca', 'Arauca', 6.481, -71.18, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Arauca","Tendencias2026"]', 'positivo', '{"neutral":24,"negativo":8,"positivo":68}', 18080, '{"Instagram":18080}', 'Conversación en Instagram en Arauca centrada en tendencias digitales y de marca. Capital: Arauca.', 'sube', 5, '["#Arauca","#Tendencias2026"]', 'hace 9 min'),
('85', 'Casanare', 'Yopal', 5.445, -71.737, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Casanare","Tendencias2026"]', 'neutral', '{"neutral":49,"negativo":11,"positivo":40}', 16400, '{"Instagram":16400}', 'Conversación en Instagram en Casanare centrada en tendencias digitales y de marca. Capital: Yopal.', 'estable', 8.6, '["#Casanare","#Tendencias2026"]', 'hace 10 min'),
('86', 'Putumayo', 'Mocoa', 0.338, -75.618, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Putumayo","Tendencias2026"]', 'neutral', '{"neutral":39,"negativo":14,"positivo":47}', 14420, '{"Instagram":14420}', 'Conversación en Instagram en Putumayo centrada en tendencias digitales y de marca. Capital: Mocoa.', 'baja', 11.6, '["#Putumayo","#Tendencias2026"]', 'hace 11 min'),
('88', 'Archipiélago de San Andrés Providencia y Santa Catalina', 'San Andrés', 13.017, -81.523, 'Debates y opiniones de la comunidad digital', '["Instagram","Archipiélago","Tendencias2026"]', 'neutral', '{"neutral":29,"negativo":17,"positivo":54}', 17240, '{"Instagram":17240}', 'Conversación en Instagram en Archipiélago de San Andrés Providencia y Santa Catalina centrada en tendencias digitales y de marca. Capital: San Andrés.', 'sube', 15.3, '["#ArchipiélagodeSanAndrésProvidenciaySantaCatalina","#Tendencias2026"]', 'hace 3 min'),
('91', 'Amazonas', 'Leticia', -1.442, -71.734, 'Contenido educativo e institucional en redes', '["Instagram","Amazonas","Tendencias2026"]', 'positivo', '{"neutral":19,"negativo":20,"positivo":61}', 15260, '{"Instagram":15260}', 'Conversación en Instagram en Amazonas centrada en tendencias digitales y de marca. Capital: Leticia.', 'estable', -5.5, '["#Amazonas","#Tendencias2026"]', 'hace 4 min'),
('94', 'Guainía', 'Inírida', 2.831, -68.86, 'Conversación sobre voluntariado y comunidad digital', '["Instagram","Guainía","Tendencias2026"]', 'positivo', '{"neutral":9,"negativo":23,"positivo":68}', 14240, '{"Instagram":14240}', 'Conversación en Instagram en Guainía centrada en tendencias digitales y de marca. Capital: Inírida.', 'baja', -2.3, '["#Guainía","#Tendencias2026"]', 'hace 5 min'),
('95', 'Guaviare', 'San José del Guaviare', 1.914, -71.868, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Guaviare","Tendencias2026"]', 'neutral', '{"neutral":52,"negativo":8,"positivo":40}', 11600, '{"Instagram":11600}', 'Conversación en Instagram en Guaviare centrada en tendencias digitales y de marca. Capital: San José del Guaviare.', 'sube', 1.2, '["#Guaviare","#Tendencias2026"]', 'hace 6 min'),
('97', 'Vaupés', 'Mitú', 0.321, -70.573, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Vaupés","Tendencias2026"]', 'neutral', '{"neutral":42,"negativo":11,"positivo":47}', 10580, '{"Instagram":10580}', 'Conversación en Instagram en Vaupés centrada en tendencias digitales y de marca. Capital: Mitú.', 'estable', 4.4, '["#Vaupés","#Tendencias2026"]', 'hace 7 min'),
('05', 'Antioquia', 'Medellín', 7.001, -75.836, 'Cobertura de marcas y creadores en Instagram', '["Instagram","Antioquia","Tendencias2026"]', 'neutral', '{"neutral":52,"negativo":8,"positivo":40}', 46160, '{"Instagram":46160}', 'Conversación en Instagram en Antioquia centrada en tendencias digitales y de marca. Capital: Medellín.', 'sube', -1.3, '["#Antioquia","#Tendencias2026"]', 'hace 3 min'),
('52', 'Nariño', 'Pasto', 1.574, -77.822, 'Reels sobre tendencias locales y actualidad regional', '["Instagram","Nariño","Tendencias2026"]', 'neutral', '{"neutral":33,"negativo":20,"positivo":47}', 26900, '{"Instagram":26900}', 'Conversación en Instagram en Nariño centrada en tendencias digitales y de marca. Capital: Pasto.', 'estable', 3, '["#Nariño","#Tendencias2026"]', 'hace 10 min'),
('99', 'Vichada', 'Puerto Carreño', 4.252, -69.261, 'Debates y opiniones de la comunidad digital', '["Instagram","Vichada","Tendencias2026"]', 'neutral', '{"neutral":32,"negativo":14,"positivo":54}', 12440, '{"Instagram":12440}', 'Conversación en Instagram en Vichada centrada en tendencias digitales y de marca. Capital: Puerto Carreño.', 'baja', 7.9, '["#Vichada","#Tendencias2026"]', 'hace 8 min')
ON CONFLICT (id) DO NOTHING;
