-- ============================================================================
-- SQL SCRIPT - INFRAESTRUCTURA CENTRO DE MANDO DIGITAL LINKTIC
-- ============================================================================
-- Instancia: https://klecvgchqqbkasedxtxj.supabase.co
-- Schema: centro_mando
-- Aislamiento completo de Autenticación, RBAC y Negocio.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS centro_mando;

-- ============================================================================
-- 1. TABLAR DE SEGURIDAD Y CONTROL (PROFILES Y ACCESOS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS centro_mando.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
    user_role TEXT DEFAULT 'viewer',
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE centro_mando.profiles DROP CONSTRAINT IF EXISTS profiles_user_role_check;
ALTER TABLE centro_mando.profiles ADD CONSTRAINT profiles_user_role_check
    CHECK (user_role IN ('superadmin', 'admin', 'viewer'));

CREATE TABLE IF NOT EXISTS centro_mando.user_screen_access (
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    screen_key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (user_id, screen_key)
);

-- ============================================================================
-- 2. FUNCIONES Y TRIGGERS DE SEGURIDAD (SECURITY DEFINER)
-- ============================================================================

CREATE OR REPLACE FUNCTION centro_mando.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM centro_mando.profiles
        WHERE id = auth.uid() AND user_role IN ('admin', 'superadmin')
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION centro_mando.is_superadmin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM centro_mando.profiles
        WHERE id = auth.uid() AND user_role = 'superadmin'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION centro_mando.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO centro_mando.profiles (id, user_role, full_name)
    VALUES (
        new.id,
        'viewer', -- Rol por defecto
        COALESCE(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'username')
    )
    ON CONFLICT (id) DO UPDATE
        SET full_name = COALESCE(EXCLUDED.full_name, centro_mando.profiles.full_name);
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created_centro_mando ON auth.users;
CREATE TRIGGER on_auth_user_created_centro_mando
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE centro_mando.handle_new_user();

-- ============================================================================
-- 3. TABLAS DE NEGOCIO Y MÉTRICAS
-- ============================================================================

-- A. Mapa Global
CREATE TABLE IF NOT EXISTS centro_mando.mapa_paises (
    id TEXT PRIMARY KEY,
    pais TEXT NOT NULL,
    emoji TEXT,
    lat NUMERIC,
    lng NUMERIC,
    tema TEXT,
    keywords JSONB DEFAULT '[]'::jsonb,
    sentimiento TEXT,
    sentimiento_pct JSONB,
    volumen NUMERIC DEFAULT 0,
    plataforma_dominante TEXT,
    plataformas JSONB,
    resumen TEXT,
    tendencia TEXT,
    pct_cambio NUMERIC DEFAULT 0,
    top_hashtags JSONB DEFAULT '[]'::jsonb,
    update_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.mapa_marcadores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pais TEXT,
    ciudad TEXT,
    lat NUMERIC,
    lng NUMERIC,
    count_num INTEGER,
    tipo TEXT,
    narrativa TEXT,
    tendencia TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- B. Conversación en Medios
CREATE TABLE IF NOT EXISTS centro_mando.medios_perfiles (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT '0%',
    sentimiento INTEGER DEFAULT 0,
    notas INTEGER DEFAULT 0,
    tendencia_semanal JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.medios_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- C. Conversación en Redes
CREATE TABLE IF NOT EXISTS centro_mando.social_perfiles (
    id TEXT PRIMARY KEY, -- 'instagram', 'facebook', 'x', 'tiktok'
    seguidores TEXT DEFAULT '0',
    interacciones INTEGER DEFAULT 0,
    alcance TEXT DEFAULT '0',
    posts INTEGER DEFAULT 0,
    sentimiento INTEGER DEFAULT 0,
    tendencia JSONB DEFAULT '[]'::jsonb,
    top_posts JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.social_feed (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    red TEXT NOT NULL,
    usuario TEXT NOT NULL,
    tiempo TEXT NOT NULL,
    texto TEXT NOT NULL,
    tipo TEXT DEFAULT 'neutral',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- D. Testigos Electorales
CREATE TABLE IF NOT EXISTS centro_mando.testigos_estrategia (
    id TEXT PRIMARY KEY, -- 'main'
    narrativa JSONB DEFAULT '{}'::jsonb,
    pilares JSONB DEFAULT '[]'::jsonb,
    noticias JSONB DEFAULT '[]'::jsonb,
    contenido JSONB DEFAULT '{}'::jsonb,
    conversacion JSONB DEFAULT '{}'::jsonb,
    pauta JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.testigos_kpis (
    id TEXT PRIMARY KEY, -- 'asignados', 'acreditados', 'misiones', 'deptos'
    label TEXT NOT NULL,
    value TEXT DEFAULT '0',
    delta TEXT DEFAULT NULL,
    progress INTEGER DEFAULT 70,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.testigos_departamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depto TEXT NOT NULL,
    count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS centro_mando.testigos_misiones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pais TEXT NOT NULL,
    ciudad TEXT NOT NULL,
    lat NUMERIC DEFAULT 0,
    lng NUMERIC DEFAULT 0,
    count INTEGER DEFAULT 0,
    tipo TEXT NOT NULL,
    narrativa TEXT DEFAULT '',
    tendencia TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- E. Actores Electorales (Mapa de Colombia)
CREATE TABLE IF NOT EXISTS centro_mando.actores_colombia (
    id TEXT PRIMARY KEY,
    nombre TEXT NOT NULL,
    capital TEXT,
    lat NUMERIC,
    lng NUMERIC,
    tema TEXT,
    keywords JSONB DEFAULT '[]'::jsonb,
    sentimiento TEXT,
    sentimiento_pct JSONB,
    volumen NUMERIC DEFAULT 0,
    plataformas JSONB DEFAULT '{"Instagram": 0}'::jsonb,
    resumen TEXT,
    tendencia TEXT,
    pct_cambio NUMERIC DEFAULT 0,
    top_hashtags JSONB DEFAULT '[]'::jsonb,
    update_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- 4. SEGURIDAD (ROW LEVEL SECURITY)
-- ============================================================================

-- Habilitar RLS en todas las tablas
ALTER TABLE centro_mando.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.user_screen_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.mapa_paises ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.mapa_marcadores ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.medios_perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.medios_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.social_perfiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.social_feed ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.testigos_estrategia ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.testigos_kpis ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.testigos_departamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.testigos_misiones ENABLE ROW LEVEL SECURITY;
ALTER TABLE centro_mando.actores_colombia ENABLE ROW LEVEL SECURITY;

-- Políticas para perfiles
DROP POLICY IF EXISTS "cne perfil lectura autenticados" ON centro_mando.profiles;
CREATE POLICY "cne perfil lectura autenticados" ON centro_mando.profiles
    FOR SELECT TO authenticated USING (id = auth.uid() OR centro_mando.is_superadmin());

DROP POLICY IF EXISTS "cne perfil escritura superadmin" ON centro_mando.profiles;
CREATE POLICY "cne perfil escritura superadmin" ON centro_mando.profiles
    FOR ALL TO authenticated USING (centro_mando.is_superadmin()) WITH CHECK (centro_mando.is_superadmin());

-- Políticas para acceso a pantallas
DROP POLICY IF EXISTS "cne accesos lectura autenticados" ON centro_mando.user_screen_access;
CREATE POLICY "cne accesos lectura autenticados" ON centro_mando.user_screen_access
    FOR SELECT TO authenticated USING (user_id = auth.uid() OR centro_mando.is_superadmin());

DROP POLICY IF EXISTS "cne accesos escritura superadmin" ON centro_mando.user_screen_access;
CREATE POLICY "cne accesos escritura superadmin" ON centro_mando.user_screen_access
    FOR ALL TO authenticated USING (centro_mando.is_superadmin()) WITH CHECK (centro_mando.is_superadmin());

-- Políticas genéricas para tablas de negocio:
-- - Lectura para cualquier usuario autenticado (justificado para visualizar métricas en el dashboard).
-- - Escritura completa restringida a administradores (según la función centro_mando.is_admin()).

DO $$
DECLARE
    table_name TEXT;
    tables_list TEXT[] := ARRAY[
        'mapa_paises', 'mapa_marcadores',
        'medios_perfiles', 'medios_feed',
        'social_perfiles', 'social_feed',
        'testigos_estrategia', 'testigos_kpis', 'testigos_departamentos', 'testigos_misiones',
        'actores_colombia'
    ];
BEGIN
    FOREACH table_name IN ARRAY tables_list
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Lectura autenticados" ON centro_mando.%I', table_name);
        EXECUTE format('CREATE POLICY "Lectura autenticados" ON centro_mando.%I FOR SELECT TO authenticated USING (true)', table_name);

        EXECUTE format('DROP POLICY IF EXISTS "Escritura administradores" ON centro_mando.%I', table_name);
        EXECUTE format('CREATE POLICY "Escritura administradores" ON centro_mando.%I FOR ALL TO authenticated USING (centro_mando.is_admin()) WITH CHECK (centro_mando.is_admin())', table_name);
    END LOOP;
END $$;

-- ============================================================================
-- 5. GRANTS Y PERMISOS DE ACCESO API (POSTGREST)
-- ============================================================================

GRANT USAGE ON SCHEMA centro_mando TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA centro_mando TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA centro_mando TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA centro_mando TO authenticated;

-- ============================================================================
-- 6. SEMILLAS DE DATOS INICIALES (DATOS DE PRUEBA)
-- ============================================================================

-- A. Mapa Global (Semillas iniciales)
INSERT INTO centro_mando.mapa_paises (id, pais, emoji, lat, lng, tema, keywords, sentimiento, sentimiento_pct, volumen, plataforma_dominante, plataformas, resumen, tendencia, pct_cambio, top_hashtags, update_time) VALUES
('CO', 'Colombia', '🇨🇴', 4.5, -74.3, 'Elecciones Presidenciales 2026 — CNE', '["CNE Colombia", "Elecciones2026", "VotoColombia", "TestigosElectorales"]', 'positivo', '{"positivo": 64, "neutral": 24, "negativo": 12}', 187400, 'TikTok', '{"X": 52000, "Instagram": 38000, "Facebook": 41000, "TikTok": 56400}', 'Alta conversación sobre el proceso electoral presidencial...', 'sube', 18.4, '["#Elecciones2026", "#CNEColombia", "#VotoColombia"]', 'hace 3 min'),
('US', 'Estados Unidos', '🇺🇸', 37.09, -95.71, 'Voto en el Exterior', '["Consulados", "Votantes", "EleccionesCO"]', 'neutral', '{"positivo": 35, "neutral": 50, "negativo": 15}', 25000, 'X', '{"X": 15000, "Instagram": 4000, "Facebook": 5000, "TikTok": 1000}', 'Conversación enfocada en la inscripción de cédulas y puestos de votación en consulados.', 'estable', 2.1, '["#VotoExterior", "#Elecciones2026"]', 'hace 10 min'),
('ES', 'España', '🇪🇸', 40.46, -3.75, 'Logística Electoral Exterior', '["Madrid", "CNE", "Inscripcion"]', 'positivo', '{"positivo": 55, "neutral": 35, "negativo": 10}', 18200, 'Instagram', '{"X": 4200, "Instagram": 8500, "Facebook": 4500, "TikTok": 1000}', 'Gran interacción sobre las fechas de cierre de inscripción de cédulas.', 'sube', 5.6, '["#CNEExterior", "#Madrid"]', 'hace 12 min')
ON CONFLICT (id) DO NOTHING;

INSERT INTO centro_mando.mapa_marcadores (pais, ciudad, lat, lng, count_num, tipo, narrativa, tendencia) VALUES
('México', 'Ciudad de México', 19.4, -99.1, 3, 'Misión OEA', 'Interés creciente en modelo electoral colombiano', 'Positiva ↑'),
('Argentina', 'Buenos Aires', -34.6, -58.4, 5, 'Observadores UNASUR', 'Solidez institucional del CNE es referente regional', 'Positiva ↑'),
('España', 'Madrid', 40.4, -3.7, 8, 'Misión UE', 'Colombia consolida democracia de calidad en Latam', 'Muy positiva ↑↑');

-- B. Conversación en Medios
INSERT INTO centro_mando.medios_perfiles (id, label, value, delta, sentimiento, notas, tendencia_semanal) VALUES
('kpi_impacto', 'Impacto Mediático', '8.4M', '+12%', 65, 0, '[]'),
('kpi_notas', 'Notas Publicadas', '342', '+5%', 0, 0, '[{"dia": "Lun", "notas": 45, "positivas": 30, "negativas": 5}, {"dia": "Mar", "notas": 52, "positivas": 35, "negativas": 8}, {"dia": "Mie", "notas": 48, "positivas": 28, "negativas": 10}, {"dia": "Jue", "notas": 65, "positivas": 40, "negativas": 12}, {"dia": "Vie", "notas": 58, "positivas": 38, "negativas": 7}, {"dia": "Sab", "notas": 34, "positivas": 20, "negativas": 4}, {"dia": "Dom", "notas": 40, "positivas": 25, "negativas": 6}]'),
('kpi_voceros', 'Voceros Activos', '12', '+0%', 80, 0, '[]'),
('kpi_alcance', 'Alcance Radial', '4.2M', '+8%', 72, 0, '[]')
ON CONFLICT (id) DO NOTHING;

INSERT INTO centro_mando.medios_feed (medio, tiempo, texto, tipo) VALUES
('El Tiempo', 'Hace 2h', 'CNE Colombia anuncia la apertura oficial de las auditorías al software de escrutinio para 2026.', 'positivo'),
('Semana', 'Hace 4h', 'Voceros del CNE responden a dudas sobre seguridad digital del censo electoral.', 'neutral'),
('El Espectador', 'Hace 6h', 'Registraduría y CNE presentan calendario unificado para inscripción de testigos electorales.', 'positivo');

-- C. Conversación en Redes
INSERT INTO centro_mando.social_perfiles (id, seguidores, sentimiento, interacciones, alcance, posts) VALUES
('instagram', '1.2M', 75, 45000, '2.5M', 124),
('facebook', '2.5M', 62, 32000, '3.8M', 89),
('x', '840K', 48, 120000, '5.2M', 450),
('tiktok', '1.5M', 82, 250000, '12M', 56)
ON CONFLICT (id) DO NOTHING;

INSERT INTO centro_mando.social_feed (red, usuario, tiempo, texto, tipo) VALUES
('instagram', '@CNE_Colombia', 'Hace 1h', '¿Ya sabes cómo registrarte como testigo electoral? Sigue este paso a paso y sé garante de la democracia. 🗳️', 'positivo'),
('x', '@cnecolombia', 'Hace 2h', 'En vivo: sesión informativa sobre auditorías internacionales a la plataforma de votación.', 'neutral'),
('tiktok', '@cne_colombia', 'Hace 4h', 'POV: Tu primera vez votando con la nueva cédula digital. 📱✨ #Democracia #CNE', 'positivo');

-- D. Testigos Electorales
INSERT INTO centro_mando.testigos_estrategia (id, narrativa, pilares, noticias, contenido, conversacion, pauta) VALUES
('main', 
 '{"gancho": "La red de testigos más grande de la historia blindará las elecciones 2026.", "tipoConversacion": "Participación + Vigilancia", "mensajeClave": "Tu voto está protegido por miles de ciudadanos.", "arco": [{"fase": "Convocatoria", "tipo": "informativo", "mensaje": "Invitación masiva a la ciudadanía."}, {"fase": "Inscripción", "tipo": "accion", "mensaje": "Meta de 150.000 testigos superada."}, {"fase": "Capacitación", "tipo": "educacion", "mensaje": "Talleres técnicos en todo el país."}, {"fase": "Despliegue", "tipo": "resultado", "mensaje": "Cobertura total en el 100% de las mesas."}]}',
 '[{"pilar": "Vigilancia Ciudadana", "icono": "👥", "color": "#2b82ee", "descripcion": "Empoderamiento del ciudadano como garante del proceso."}, {"pilar": "Capacitación Técnica", "icono": "📚", "color": "#f3b116", "descripcion": "Formación rigurosa en normatividad y software."}, {"pilar": "Cobertura Nacional", "icono": "📍", "color": "#2eb88a", "descripcion": "Presencia efectiva en los 32 departamentos."}]',
 '[{"medio": "El Tiempo", "titulo": "CNE abre inscripciones para testigos electorales 2026", "fecha": "Hace 1d", "categoria": "Convocatoria", "url": "#"}, {"medio": "W Radio", "titulo": "Misiones internacionales avalan plan de testigos del CNE", "fecha": "Hace 5h", "categoria": "Internacional", "url": "#"}]',
 '{"instagram": [{"formato": "Reel", "idea": "POV: Mi día como testigo electoral", "tipo": "Inspiracional"}], "facebook": [{"formato": "Post", "idea": "Guía paso a paso para inscribirte", "tipo": "Informativo"}], "x": [{"formato": "Hilo", "idea": "Por qué los testigos son la base de la confianza", "tipo": "Pedagogía"}], "tiktok": [{"formato": "Tutorial", "idea": "Cómo usar la app de testigos", "tipo": "Técnico"}]}',
 '{"instagram": {"menciones": 3200, "sentimiento": 78, "volumePeak": "Lunes 18:00", "topHashtags": ["#TestigosElectorales", "#VotoSeguro"]}, "facebook": {"menciones": 4500, "sentimiento": 72, "volumePeak": "Martes 10:00", "topHashtags": ["#Democracia", "#CNE"]}, "x": {"menciones": 12000, "sentimiento": 65, "volumePeak": "Jueves 09:00", "topHashtags": ["#VigilanciaCiudadana"]}, "tiktok": {"menciones": 8500, "sentimiento": 82, "volumePeak": "Viernes 20:00", "topHashtags": ["#SoyTestigo"]}}',
 '[{"formato": "Story", "objetivo": "Conversión", "presupuesto": "Alto", "cta": "Inscríbete aquí", "segmento": "Jóvenes 18-35", "plataforma": ["Instagram", "Facebook"]}]'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO centro_mando.testigos_kpis (id, label, value, delta, progress) VALUES
('asignados', 'Total Asignados', '142.800', NULL, 70),
('acreditados', 'Acreditados', '98.430', '+69%', 70),
('misiones', 'Misiones Internacionales', '12', NULL, 70),
('deptos', 'Dpto. Cubiertos', '32', NULL, 70)
ON CONFLICT (id) DO NOTHING;

INSERT INTO centro_mando.testigos_departamentos (depto, count) VALUES
('Bogotá', 28000),
('Antioquia', 22000),
('Valle', 18500),
('Atlántico', 12000),
('Cundinamarca', 9800),
('Otros', 8130);

INSERT INTO centro_mando.testigos_misiones (pais, ciudad, lat, lng, count, tipo, narrativa, tendencia) VALUES
('México', 'Ciudad de México', 19.4, -99.1, 3, 'Misión OEA', 'Interés creciente en modelo electoral colombiano', 'Positiva ↑'),
('Argentina', 'Buenos Aires', -34.6, -58.4, 5, 'Observadores UNASUR', 'Solidez institucional del CNE es referente regional', 'Positiva ↑'),
('España', 'Madrid', 40.4, -3.7, 8, 'Misión UE', 'Colombia consolida democracia de calidad en Latam', 'Muy positiva ↑↑'),
('Estados Unidos', 'Washington D.C.', 38.9, -77, 12, 'Carter Center', 'Proceso técnico sólido, seguimiento del software electoral', 'Positiva ↑');

-- E. Actores Electorales (Mapa de Colombia)
INSERT INTO centro_mando.actores_colombia
(id, nombre, capital, lat, lng, tema, keywords, sentimiento, sentimiento_pct, volumen, plataformas, resumen, tendencia, pct_cambio, top_hashtags, update_time)
VALUES
('05', 'Antioquia', 'Medellín', 7.001, -75.836, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Antioquia"]', 'neutral', '{"positivo":40,"neutral":52,"negativo":8}', 46160, '{"Instagram":46160}', 'Conversación en Instagram en Antioquia centrada en el proceso electoral 2026. Capital: Medellín.', 'sube', -1.3, '["#Elecciones2026","#CNEColombia","#Antioquia"]', 'hace 3 min'),
('08', 'Atlántico', 'Barranquilla', 10.675, -74.973, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Atlántico"]', 'neutral', '{"positivo":47,"neutral":42,"negativo":11}', 36500, '{"Instagram":36500}', 'Conversación en Instagram en Atlántico centrada en el proceso electoral 2026. Capital: Barranquilla.', 'estable', 0.8, '["#Elecciones2026","#CNEColombia","#Atlántico"]', 'hace 4 min'),
('11', 'Santafé de Bogotá D.C', 'Bogotá', 4.286, -74.211, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Santafé"]', 'neutral', '{"positivo":54,"neutral":32,"negativo":14}', 51800, '{"Instagram":51800}', 'Conversación en Instagram en Santafé de Bogotá D.C centrada en el proceso electoral 2026. Capital: Bogotá.', 'baja', 6, '["#Elecciones2026","#CNEColombia","#SantafédeBogotáDC"]', 'hace 5 min'),
('13', 'Bolívar', 'Cartagena', 9.125, -74.764, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Bolívar"]', 'positivo', '{"positivo":61,"neutral":22,"negativo":17}', 36380, '{"Instagram":36380}', 'Conversación en Instagram en Bolívar centrada en el proceso electoral 2026. Capital: Cartagena.', 'sube', 7.4, '["#Elecciones2026","#CNEColombia","#Bolívar"]', 'hace 6 min'),
('15', 'Boyacá', 'Tunja', 5.849, -73.295, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Boyacá"]', 'positivo', '{"positivo":68,"neutral":12,"negativo":20}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Boyacá centrada en el proceso electoral 2026. Capital: Tunja.', 'estable', 9.8, '["#Elecciones2026","#CNEColombia","#Boyacá"]', 'hace 7 min'),
('17', 'Caldas', 'Manizales', 5.351, -75.38, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Caldas"]', 'negativo', '{"positivo":40,"neutral":37,"negativo":23}', 24080, '{"Instagram":24080}', 'Conversación en Instagram en Caldas centrada en el proceso electoral 2026. Capital: Manizales.', 'baja', 13, '["#Elecciones2026","#CNEColombia","#Caldas"]', 'hace 8 min'),
('18', 'Caquetá', 'Florencia', 0.667, -73.81, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Caquetá"]', 'neutral', '{"positivo":47,"neutral":45,"negativo":8}', 17300, '{"Instagram":17300}', 'Conversación en Instagram en Caquetá centrada en el proceso electoral 2026. Capital: Florencia.', 'sube', 15.4, '["#Elecciones2026","#CNEColombia","#Caquetá"]', 'hace 9 min'),
('19', 'Cauca', 'Popayán', 2.324, -76.835, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Cauca"]', 'neutral', '{"positivo":54,"neutral":35,"negativo":11}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Cauca centrada en el proceso electoral 2026. Capital: Popayán.', 'estable', -3.7, '["#Elecciones2026","#CNEColombia","#Cauca"]', 'hace 10 min'),
('20', 'Cesar', 'Valledupar', 9.29, -73.524, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Cesar"]', 'positivo', '{"positivo":61,"neutral":25,"negativo":14}', 25820, '{"Instagram":25820}', 'Conversación en Instagram en Cesar centrada en el proceso electoral 2026. Capital: Valledupar.', 'baja', -0.8, '["#Elecciones2026","#CNEColombia","#Cesar"]', 'hace 11 min'),
('23', 'Córdoba', 'Montería', 8.531, -75.697, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Córdoba"]', 'positivo', '{"positivo":68,"neutral":15,"negativo":17}', 28640, '{"Instagram":28640}', 'Conversación en Instagram en Córdoba centrada en el proceso electoral 2026. Capital: Montería.', 'sube', 2.9, '["#Elecciones2026","#CNEColombia","#Córdoba"]', 'hace 3 min'),
('25', 'Cundinamarca', 'Bogotá', 4.755, -74.174, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Cundinamarca"]', 'neutral', '{"positivo":40,"neutral":40,"negativo":20}', 37520, '{"Instagram":37520}', 'Conversación en Instagram en Cundinamarca centrada en el proceso electoral 2026. Capital: Bogotá.', 'estable', 7.8, '["#Elecciones2026","#CNEColombia","#Cundinamarca"]', 'hace 4 min'),
('27', 'Chocó', 'Quibdó', 6.016, -77.004, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Chocó"]', 'negativo', '{"positivo":47,"neutral":30,"negativo":23}', 19220, '{"Instagram":19220}', 'Conversación en Instagram en Chocó centrada en el proceso electoral 2026. Capital: Quibdó.', 'baja', 8.8, '["#Elecciones2026","#CNEColombia","#Chocó"]', 'hace 5 min'),
('41', 'Huila', 'Neiva', 2.665, -75.602, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Huila"]', 'neutral', '{"positivo":54,"neutral":38,"negativo":8}', 25400, '{"Instagram":25400}', 'Conversación en Instagram en Huila centrada en el proceso electoral 2026. Capital: Neiva.', 'sube', 12.9, '["#Elecciones2026","#CNEColombia","#Huila"]', 'hace 6 min'),
('44', 'La Guajira', 'Riohacha', 11.452, -72.493, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","La"]', 'positivo', '{"positivo":61,"neutral":28,"negativo":11}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en La Guajira centrada en el proceso electoral 2026. Capital: Riohacha.', 'estable', 16, '["#Elecciones2026","#CNEColombia","#LaGuajira"]', 'hace 7 min'),
('47', 'Magdalena', 'Santa Marta', 10.189, -74.265, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Magdalena"]', 'positivo', '{"positivo":68,"neutral":18,"negativo":14}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Magdalena centrada en el proceso electoral 2026. Capital: Santa Marta.', 'baja', -3.8, '["#Elecciones2026","#CNEColombia","#Magdalena"]', 'hace 8 min'),
('50', 'Meta', 'Villavicencio', 3.218, -73.111, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Meta"]', 'neutral', '{"positivo":40,"neutral":43,"negativo":17}', 28400, '{"Instagram":28400}', 'Conversación en Instagram en Meta centrada en el proceso electoral 2026. Capital: Villavicencio.', 'sube', -0.1, '["#Elecciones2026","#CNEColombia","#Meta"]', 'hace 9 min'),
('52', 'Nariño', 'Pasto', 1.574, -77.822, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Nariño"]', 'neutral', '{"positivo":47,"neutral":33,"negativo":20}', 26900, '{"Instagram":26900}', 'Conversación en Instagram en Nariño centrada en el proceso electoral 2026. Capital: Pasto.', 'estable', 3, '["#Elecciones2026","#CNEColombia","#Nariño"]', 'hace 10 min'),
('54', 'Norte de Santander', 'Cúcuta', 7.871, -72.949, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Norte"]', 'negativo', '{"positivo":54,"neutral":23,"negativo":23}', 30680, '{"Instagram":30680}', 'Conversación en Instagram en Norte de Santander centrada en el proceso electoral 2026. Capital: Cúcuta.', 'baja', 6.8, '["#Elecciones2026","#CNEColombia","#NortedeSantander"]', 'hace 11 min'),
('63', 'Quindío', 'Armenia', 4.498, -75.702, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Quindío"]', 'positivo', '{"positivo":61,"neutral":31,"negativo":8}', 23900, '{"Instagram":23900}', 'Conversación en Instagram en Quindío centrada en el proceso electoral 2026. Capital: Armenia.', 'sube', 9.2, '["#Elecciones2026","#CNEColombia","#Quindío"]', 'hace 3 min'),
('66', 'Risaralda', 'Pereira', 5.061, -75.893, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Risaralda"]', 'positivo', '{"positivo":68,"neutral":21,"negativo":11}', 29600, '{"Instagram":29600}', 'Conversación en Instagram en Risaralda centrada en el proceso electoral 2026. Capital: Pereira.', 'estable', 13.2, '["#Elecciones2026","#CNEColombia","#Risaralda"]', 'hace 4 min'),
('68', 'Santander', 'Bucaramanga', 6.611, -73.428, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Santander"]', 'neutral', '{"positivo":40,"neutral":46,"negativo":14}', 34640, '{"Instagram":34640}', 'Conversación en Instagram en Santander centrada en el proceso electoral 2026. Capital: Bucaramanga.', 'baja', 17.7, '["#Elecciones2026","#CNEColombia","#Santander"]', 'hace 5 min'),
('70', 'Sucre', 'Sincelejo', 9.135, -75.206, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Sucre"]', 'neutral', '{"positivo":47,"neutral":36,"negativo":17}', 20180, '{"Instagram":20180}', 'Conversación en Instagram en Sucre centrada en el proceso electoral 2026. Capital: Sincelejo.', 'sube', -4.6, '["#Elecciones2026","#CNEColombia","#Sucre"]', 'hace 6 min'),
('73', 'Tolima', 'Ibagué', 4.076, -75.212, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Tolima"]', 'neutral', '{"positivo":54,"neutral":26,"negativo":20}', 28760, '{"Instagram":28760}', 'Conversación en Instagram en Tolima centrada en el proceso electoral 2026. Capital: Ibagué.', 'estable', -0.3, '["#Elecciones2026","#CNEColombia","#Tolima"]', 'hace 7 min'),
('76', 'Valle del Cauca', 'Cali', 3.98, -76.566, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Valle"]', 'positivo', '{"positivo":61,"neutral":16,"negativo":23}', 47900, '{"Instagram":47900}', 'Conversación en Instagram en Valle del Cauca centrada en el proceso electoral 2026. Capital: Cali.', 'baja', 5.4, '["#Elecciones2026","#CNEColombia","#ValledelCauca"]', 'hace 8 min'),
('81', 'Arauca', 'Arauca', 6.481, -71.18, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Arauca"]', 'positivo', '{"positivo":68,"neutral":24,"negativo":8}', 18080, '{"Instagram":18080}', 'Conversación en Instagram en Arauca centrada en el proceso electoral 2026. Capital: Arauca.', 'sube', 5, '["#Elecciones2026","#CNEColombia","#Arauca"]', 'hace 9 min'),
('85', 'Casanare', 'Yopal', 5.445, -71.737, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Casanare"]', 'neutral', '{"positivo":40,"neutral":49,"negativo":11}', 16400, '{"Instagram":16400}', 'Conversación en Instagram en Casanare centrada en el proceso electoral 2026. Capital: Yopal.', 'estable', 8.6, '["#Elecciones2026","#CNEColombia","#Casanare"]', 'hace 10 min'),
('86', 'Putumayo', 'Mocoa', 0.338, -75.618, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Putumayo"]', 'neutral', '{"positivo":47,"neutral":39,"negativo":14}', 14420, '{"Instagram":14420}', 'Conversación en Instagram en Putumayo centrada en el proceso electoral 2026. Capital: Mocoa.', 'baja', 11.6, '["#Elecciones2026","#CNEColombia","#Putumayo"]', 'hace 11 min'),
('88', 'Archipiélago de San Andrés Providencia y Santa Catalina', 'San Andrés', 13.017, -81.523, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Archipiélago"]', 'neutral', '{"positivo":54,"neutral":29,"negativo":17}', 17240, '{"Instagram":17240}', 'Conversación en Instagram en Archipiélago de San Andrés Providencia y Santa Catalina centrada en el proceso electoral 2026. Capital: San Andrés.', 'sube', 15.3, '["#Elecciones2026","#CNEColombia","#ArchipiélagodeSanAndrésProvidenciaySantaCatalina"]', 'hace 3 min'),
('91', 'Amazonas', 'Leticia', -1.442, -71.734, 'Pedagogía electoral del CNE en redes', '["Elecciones2026","CNE","Instagram","Amazonas"]', 'positivo', '{"positivo":61,"neutral":19,"negativo":20}', 15260, '{"Instagram":15260}', 'Conversación en Instagram en Amazonas centrada en el proceso electoral 2026. Capital: Leticia.', 'estable', -5.5, '["#Elecciones2026","#CNEColombia","#Amazonas"]', 'hace 4 min'),
('94', 'Guainía', 'Inírida', 2.831, -68.86, 'Conversación sobre testigos electorales', '["Elecciones2026","CNE","Instagram","Guainía"]', 'positivo', '{"positivo":68,"neutral":9,"negativo":23}', 14240, '{"Instagram":14240}', 'Conversación en Instagram en Guainía centrada en el proceso electoral 2026. Capital: Inírida.', 'baja', -2.3, '["#Elecciones2026","#CNEColombia","#Guainía"]', 'hace 5 min'),
('95', 'Guaviare', 'San José del Guaviare', 1.914, -71.868, 'Cobertura de campañas y candidatos en Instagram', '["Elecciones2026","CNE","Instagram","Guaviare"]', 'neutral', '{"positivo":40,"neutral":52,"negativo":8}', 11600, '{"Instagram":11600}', 'Conversación en Instagram en Guaviare centrada en el proceso electoral 2026. Capital: San José del Guaviare.', 'sube', 1.2, '["#Elecciones2026","#CNEColombia","#Guaviare"]', 'hace 6 min'),
('97', 'Vaupés', 'Mitú', 0.321, -70.573, 'Reels sobre cédula y puestos de votación', '["Elecciones2026","CNE","Instagram","Vaupés"]', 'neutral', '{"positivo":47,"neutral":42,"negativo":11}', 10580, '{"Instagram":10580}', 'Conversación en Instagram en Vaupés centrada en el proceso electoral 2026. Capital: Mitú.', 'estable', 4.4, '["#Elecciones2026","#CNEColombia","#Vaupés"]', 'hace 7 min'),
('99', 'Vichada', 'Puerto Carreño', 4.252, -69.261, 'Debates y propuestas de actores electorales', '["Elecciones2026","CNE","Instagram","Vichada"]', 'neutral', '{"positivo":54,"neutral":32,"negativo":14}', 12440, '{"Instagram":12440}', 'Conversación en Instagram en Vichada centrada en el proceso electoral 2026. Capital: Puerto Carreño.', 'baja', 7.9, '["#Elecciones2026","#CNEColombia","#Vichada"]', 'hace 8 min')
ON CONFLICT (id) DO NOTHING;
